### ISSUE TITLE
Unable to solve matching problem

### ISSUE THREAD

**Issue by lirwin3007** [uestla/Simplex-Calculator#2]
Hi, I'm trying to solve a linear programming problem as follows:
```
MAX Z = -5x1 - 7x2 - 10x3 - 6x4
subject to
x1 + x2 <= 1
x3 + x4 <= 1
x1 + x3 = 1
x2 + x4 = 1
and x1,x2,x3,x4 >= 0 
```

When I put this into the online demo:
![image](https://user-images.githubusercontent.com/25307526/64109887-86a15380-cd78-11e9-8e7c-c06138ba005b.png)

It tells me 

> This task has no optimal solution.

However, I know this isn't the case since I can work this out manually and get an optimal solution of x1=1, x2=0, x3=0, x4=1.

I can also use this other online calculator to get the correct result:
[Link](https://cbom.atozmath.com/CBOM/Simplex.aspx?q=sm&q1=4%604%60MAX%60Z%60x1%2Cx2%2Cx3%2Cx4%60-5%2C-7%2C-10%2C-6%601%2C1%2C0%2C0%3B0%2C0%2C1%2C1%3B1%2C0%2C1%2C0%3B0%2C1%2C0%2C1%60%3C%3D%2C%3C%3D%2C%3D%2C%3D%601%2C1%2C1%2C1%60%60A%60false%60true%60false%60true%60false%60false%60true&do=1#tblSolution)

I'm struggling to understand why I'm getting different results from the 2 calculators

**Comment by uestla** [comment]
Hello,

to be honest it is quite a long time since I wrote this and my physical memory is very limited :-D
But maybe if you'd checkout this project and wrote a test task with your equations (see [Task1.phpt](https://github.com/uestla/Simplex-Calculator/blob/8d3b9880bf7c508cf402c783ef9af5eef3bce69b/tests/tasks/Task1.phpt) as an example), you could help with fixing the problem?

Thanks in advance!

**Comment by uestla** [comment]
Inactive - closing.
